// Run against the isolated preview-fixture.js, never against the working database.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{for(const width of [390,1280]){
  const page=await browser.newPage({viewport:{width,height:844}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:3037',{waitUntil:'networkidle'});
  await page.evaluate(()=>Auth.login('student@fixture.test','DemoPassword123!'));
  await page.evaluate(()=>navigate('advisor'));
  await page.locator('#planner-panel > summary').click();
  await page.locator('#planner-form [type=submit]').click();
  await page.waitForFunction(()=>document.getElementById('planner-status').textContent.includes('Сколько баллов'));
  await page.locator('#planner-form [name=ent]').fill('110');
  await page.locator('#planner-form [name=budget]').fill('2000000');
  for(const [name,value] of Object.entries({subject1:'math',subject2:'informatics',group:'B057',year:'2027',funding:'paid',language:'any'}))await page.locator(`#planner-form [name=${name}]`).selectOption(value);
  await page.locator('#planner-form [type=submit]').click();
  await page.locator('.planner-options input[value="iitu-cs"]').check();
  const card=page.locator('.planner-option').filter({has:page.locator('input[value="iitu-cs"]')});
  assert.match(await card.textContent(),/Первый курс · 2027: Не подтверждено/);
  assert.match(await card.locator('.planner-reference').textContent(),/Справочно за 2026/);
  assert.match(await card.locator('.planner-warning').textContent(),/Требует проверки/);
  await page.locator('#planner-agent').click();
  await page.waitForFunction(()=>document.getElementById('planner-status').textContent.includes('подбор по правилам без ИИ'));
  await page.locator('.planner-options input[value="iitu-cs"]').check();
  await page.locator('#planner-compare').click();
  assert.equal(await page.locator('#planner-comparison tbody tr').count(),1);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),width);
  await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),`planner-comparison-${width}.png`)});
  const checkedPlan=require('../programme-planner').buildProgrammePlan({ent:110,budget:2000000,subjects:['math','informatics'],group:'B057',year:2027,funding:'paid',language:'any'},new Date(),{iitu:{id:'iitu',status:'unavailable'}});
  let releaseSource;
  const sourceGate=new Promise(resolve=>{releaseSource=resolve;});
  await page.route('**/api/planner/sources/check',async route=>{await sourceGate;await route.fulfill({json:{sources:[{id:'iitu',status:'unavailable',checkedAt:new Date().toISOString()}],plan:checkedPlan}});});
  await page.locator('#planner-check-sources').click();
  await page.locator('.planner-options input[value="iitu-cs"]').uncheck();
  await page.locator('.planner-options input[value="iitu-cs"]').check();
  assert.equal(await page.locator('#planner-save').isDisabled(),true);
  releaseSource();
  await page.waitForFunction(()=>document.getElementById('planner-source-status').textContent.includes('недоступен'));
  assert.equal(await page.locator('.planner-options input:checked').count(),0);
  assert.equal(await page.locator('#planner-comparison tbody tr').count(),0);
  assert.match(await page.locator('#planner-result').textContent(),/ручной перепроверки/);
  await page.locator('.planner-options input[value="iitu-cs"]').check();
  await page.route('**/api/planner/interpret',route=>route.fulfill({json:{status:'fallback',reason:'quota'}}));
  await page.locator('#planner-panel > details > summary').click();
  await page.locator('#planner-message').fill('ЕНТ 110');
  await page.locator('#planner-interpret').click();
  await page.waitForFunction(()=>document.getElementById('planner-status').textContent.includes('Исчерпан баланс'));
  assert.equal(await page.locator('#planner-form [name=ent]').inputValue(),'110');
  await page.locator('#planner-save').click();
  await page.waitForFunction(()=>document.getElementById('planner-status').textContent.includes('Сохранено'));
  await page.evaluate(()=>navigate('profile'));
  await page.locator('#planner-saved > summary').click();
  await page.locator('[data-task]').first().check();
  assert.match(await page.locator('.planner-snapshot-review').first().textContent(),/без нового запроса к сайтам/);
  assert.match(await page.locator('.planner-snapshot-review').first().textContent(),/Первый курс · 2027: Не подтверждено/);
  await page.waitForFunction(()=>!document.querySelector('[data-task]').disabled);
  await page.locator('#planner-saved > summary').click();
  await page.locator('#planner-saved > summary').click();
  await page.waitForFunction(()=>document.querySelector('[data-task]')?.checked);
  await page.locator('[data-restore]').first().click();
  await page.locator('.planner-options input[value="iitu-cs"]').waitFor();
  // A valid but incompatible pair must yield no selectable programmes.
  await page.locator('#planner-form [name=subject1]').selectOption('biology');
  await page.locator('#planner-form [name=subject2]').selectOption('chemistry');
  await page.locator('#planner-form [type=submit]').click();
  await page.waitForFunction(()=>document.getElementById('planner-result').textContent.includes('Совпадений'));
  assert.equal(await page.locator('.planner-options input').count(),0);
  // Historical intake: show expired deadline and budget gap, not a false eligible result.
  await page.locator('#planner-form [name=subject1]').selectOption('math');
  await page.locator('#planner-form [name=subject2]').selectOption('informatics');
  await page.locator('#planner-form [name=year]').selectOption('2026');
  await page.locator('#planner-form [name=budget]').fill('50000');
  await page.locator('#planner-form [name=city]').selectOption('Алматы');
  await page.locator('#planner-form [type=submit]').click();
  await page.waitForFunction(()=>document.getElementById('planner-result').textContent.includes('не хватает'));
  assert.equal(await page.locator('.planner-options input').count(),0);
  await page.evaluate(()=>Auth.clearSession());
  assert.equal(await page.locator('#planner-saved-list').textContent(),'');
  assert.equal(await page.locator('#planner-form [name=ent]').inputValue(),'');
  assert.deepEqual(errors,[]);
  console.log(`PASS ${width}: source alerts/recalculation and AI fallback UI (mocked), real API selection/save/tasks/restore, validation, session clearing`);
  await page.screenshot({path:require('node:path').join(require('node:os').tmpdir(),`planner-v2-${width}.png`)});
  await page.close();
 }
 const kk=await browser.newPage({viewport:{width:390,height:844}});
 await kk.addInitScript(()=>localStorage.setItem('language','kk'));
 await kk.goto('http://127.0.0.1:3037',{waitUntil:'networkidle'});
 await kk.evaluate(()=>navigate('advisor'));
 await kk.locator('#planner-panel > summary').click();
 await kk.locator('#planner-form [type=submit]').click();
 await kk.waitForFunction(()=>document.getElementById('planner-status').textContent.includes('ҰБТ балыңыз'));
 assert.match(await kk.locator('#planner-panel > summary').textContent(),/көмекшісі/);
 await kk.close();console.log('PASS Kazakh clarification and labels');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
